"""
BountyOS - Master Tool Catalogue

Complete registry of every known security tool across:
  - Parrot OS Security Edition
  - Kali Linux
  - BlackArch
  - Ubuntu / Debian (with manual installs)
  - macOS (via Homebrew)
  - Any OS with Go/Python/Ruby tooling

Each entry defines:
  binary      : executable name checked in PATH
  name        : canonical tool name used in BountyOS
  phase       : recon | vulnscan | exploit | post | forensics | wireless | crypto | util
  category    : sub-category for grouping in dashboard
  description : one-line description
  version_flag: flag to confirm tool is functional (not just present)
  timeout     : default subprocess timeout in seconds
  output_fmt  : raw | json | xml | grep — how to parse output
  finding_patterns: regex patterns that indicate a finding in raw output
  install_hint: how to install if missing
"""

TOOL_CATALOGUE = [

    # ═══════════════════════════════════════════════════════════════════════════
    # RECON — Subdomain & DNS
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "subfinder",
        "name": "subfinder",
        "phase": "recon",
        "category": "subdomain",
        "description": "Passive subdomain enumeration via multiple sources",
        "version_flag": "-version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\.[a-z]{2,}$"],
        "install_hint": "go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        "default_args": "-silent",
        "target_flag": "-d",
    },
    {
        "binary": "amass",
        "name": "amass",
        "phase": "recon",
        "category": "subdomain",
        "description": "In-depth subdomain enumeration via DNS, certs, scraping",
        "version_flag": "version",
        "timeout": 600,
        "output_fmt": "raw",
        "finding_patterns": [r"\.[a-z]{2,}$"],
        "install_hint": "go install github.com/owasp-amass/amass/v4/...@master",
        "default_args": "enum -passive",
        "target_flag": "-d",
    },
    {
        "binary": "dnsx",
        "name": "dnsx",
        "phase": "recon",
        "category": "subdomain",
        "description": "Fast DNS resolution and brute-forcing",
        "version_flag": "-version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"],
        "install_hint": "go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest",
        "default_args": "-silent -resp",
        "target_flag": "-d",
    },
    {
        "binary": "dnsrecon",
        "name": "dnsrecon",
        "phase": "recon",
        "category": "subdomain",
        "description": "DNS enumeration: zone transfers, brute-force, SRV records",
        "version_flag": "--version",
        "timeout": 180,
        "output_fmt": "raw",
        "finding_patterns": [r"A\s+", r"CNAME\s+", r"MX\s+", r"\[\\+\]"],
        "install_hint": "apt install dnsrecon",
        "default_args": "-t std,axfr,brt",
        "target_flag": "-d",
    },
    {
        "binary": "dnsenum",
        "name": "dnsenum",
        "phase": "recon",
        "category": "subdomain",
        "description": "DNS enumeration including zone transfers and Google scraping",
        "version_flag": "--version",
        "timeout": 180,
        "output_fmt": "raw",
        "finding_patterns": [r"Found", r"Zone Transfer"],
        "install_hint": "apt install dnsenum",
        "default_args": "--nocolor",
        "target_flag": "",
    },
    {
        "binary": "fierce",
        "name": "fierce",
        "phase": "recon",
        "category": "subdomain",
        "description": "DNS brute-forcing and zone transfer scanner",
        "version_flag": "--version",
        "timeout": 180,
        "output_fmt": "raw",
        "finding_patterns": [r"Found:", r"Nearby:"],
        "install_hint": "apt install fierce",
        "default_args": "",
        "target_flag": "--domain",
    },
    {
        "binary": "massdns",
        "name": "massdns",
        "phase": "recon",
        "category": "subdomain",
        "description": "High-performance DNS resolver for massive subdomain lists",
        "version_flag": "--help",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"NOERROR"],
        "install_hint": "apt install massdns",
        "default_args": "-r /usr/share/massdns/lists/resolvers.txt -t A",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # RECON — Port & Service Scanning
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "nmap",
        "name": "nmap",
        "phase": "recon",
        "category": "portscan",
        "description": "Network mapper — port scanning, service detection, NSE scripts",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\d+/tcp\s+open", r"\d+/udp\s+open"],
        "install_hint": "apt install nmap",
        "default_args": "-sV --open -T4",
        "target_flag": "",
    },
    {
        "binary": "masscan",
        "name": "masscan",
        "phase": "recon",
        "category": "portscan",
        "description": "Fastest port scanner — millions of packets per second",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"Discovered open port"],
        "install_hint": "apt install masscan",
        "default_args": "--rate=1000",
        "target_flag": "",
    },
    {
        "binary": "rustscan",
        "name": "rustscan",
        "phase": "recon",
        "category": "portscan",
        "description": "Ultra-fast port scanner written in Rust",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"Open \d+\.\d+"],
        "install_hint": "cargo install rustscan",
        "default_args": "--ulimit 5000",
        "target_flag": "-a",
    },
    {
        "binary": "unicornscan",
        "name": "unicornscan",
        "phase": "recon",
        "category": "portscan",
        "description": "Asynchronous stateless TCP/UDP port scanner",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"open\["],
        "install_hint": "apt install unicornscan",
        "default_args": "-mT",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # RECON — Web Fingerprinting & Probing
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "httpx",
        "name": "httpx",
        "phase": "recon",
        "category": "webprobe",
        "description": "Fast HTTP probing — status, title, tech detection",
        "version_flag": "-version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\[200\]", r"\[301\]", r"\[403\]"],
        "install_hint": "go install github.com/projectdiscovery/httpx/cmd/httpx@latest",
        "default_args": "-silent -title -tech-detect -status-code",
        "target_flag": "-u",
    },
    {
        "binary": "whatweb",
        "name": "whatweb",
        "phase": "recon",
        "category": "webprobe",
        "description": "Web technology fingerprinting",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"\[", r"WordPress", r"Apache", r"nginx"],
        "install_hint": "apt install whatweb",
        "default_args": "--color=never",
        "target_flag": "",
    },
    {
        "binary": "wafw00f",
        "name": "wafw00f",
        "phase": "recon",
        "category": "webprobe",
        "description": "WAF detection and fingerprinting",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"is behind", r"WAF"],
        "install_hint": "pip install wafw00f",
        "default_args": "-a",
        "target_flag": "",
    },
    {
        "binary": "gowitness",
        "name": "gowitness",
        "phase": "recon",
        "category": "webprobe",
        "description": "Web screenshot tool for discovered services",
        "version_flag": "version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"screenshot"],
        "install_hint": "go install github.com/sensepost/gowitness@latest",
        "default_args": "single",
        "target_flag": "--url",
    },
    {
        "binary": "aquatone",
        "name": "aquatone",
        "phase": "recon",
        "category": "webprobe",
        "description": "Domain flyover with screenshots and reporting",
        "version_flag": "-version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"Screenshotted"],
        "install_hint": "Download from github.com/michenriksen/aquatone/releases",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # RECON — OSINT & Data Gathering
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "theharvester",
        "name": "theharvester",
        "phase": "recon",
        "category": "osint",
        "description": "Email, hostname, subdomain OSINT from public sources",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[\*\]", r"@", r"IP:"],
        "install_hint": "apt install theharvester",
        "default_args": "-b google,bing,linkedin,dnsdumpster",
        "target_flag": "-d",
    },
    {
        "binary": "recon-ng",
        "name": "recon-ng",
        "phase": "recon",
        "category": "osint",
        "description": "Full-featured OSINT reconnaissance framework",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[.*\]"],
        "install_hint": "apt install recon-ng",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "maltego",
        "name": "maltego",
        "phase": "recon",
        "category": "osint",
        "description": "Visual link analysis and OSINT platform",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install maltego",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "dmitry",
        "name": "dmitry",
        "phase": "recon",
        "category": "osint",
        "description": "Deepmagic information gathering — whois, ports, emails",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"Found", r"Record"],
        "install_hint": "apt install dmitry",
        "default_args": "-winsepfb",
        "target_flag": "",
    },
    {
        "binary": "gau",
        "name": "gau",
        "phase": "recon",
        "category": "osint",
        "description": "Get all URLs from Wayback Machine, Common Crawl, OTX",
        "version_flag": "--version",
        "timeout": 180,
        "output_fmt": "raw",
        "finding_patterns": [r"https?://"],
        "install_hint": "go install github.com/lc/gau/v2/cmd/gau@latest",
        "default_args": "--subs",
        "target_flag": "",
    },
    {
        "binary": "waybackurls",
        "name": "waybackurls",
        "phase": "recon",
        "category": "osint",
        "description": "Fetch all URLs from Wayback Machine",
        "version_flag": "-h",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"https?://"],
        "install_hint": "go install github.com/tomnomnom/waybackurls@latest",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "shodan",
        "name": "shodan",
        "phase": "recon",
        "category": "osint",
        "description": "Shodan CLI — search indexed internet-facing services",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"IP:", r"Port:", r"Vulns:"],
        "install_hint": "pip install shodan",
        "default_args": "host",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # VULN SCAN — Web Application
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "nuclei",
        "name": "nuclei",
        "phase": "vulnscan",
        "category": "webapp",
        "description": "Template-based vulnerability scanner",
        "version_flag": "-version",
        "timeout": 600,
        "output_fmt": "json",
        "finding_patterns": [r"\[critical\]", r"\[high\]", r"\[medium\]"],
        "install_hint": "go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
        "default_args": "-severity medium,high,critical -silent -json",
        "target_flag": "-u",
    },
    {
        "binary": "nikto",
        "name": "nikto",
        "phase": "vulnscan",
        "category": "webapp",
        "description": "Web server misconfiguration and vuln scanner",
        "version_flag": "-Version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\+ ", r"OSVDB", r"CVE-"],
        "install_hint": "apt install nikto",
        "default_args": "-nointeractive",
        "target_flag": "-h",
    },
    {
        "binary": "ffuf",
        "name": "ffuf",
        "phase": "vulnscan",
        "category": "fuzzing",
        "description": "Fast web fuzzer for directories, files, parameters",
        "version_flag": "-V",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[Status: 200\]", r"\[Status: 301\]", r"\[Status: 403\]"],
        "install_hint": "go install github.com/ffuf/ffuf/v2@latest",
        "default_args": "-mc 200,201,301,302,403 -silent",
        "target_flag": "-u",
    },
    {
        "binary": "feroxbuster",
        "name": "feroxbuster",
        "phase": "vulnscan",
        "category": "fuzzing",
        "description": "Fast recursive content discovery tool",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"200\s+", r"301\s+", r"403\s+"],
        "install_hint": "apt install feroxbuster",
        "default_args": "--silent --no-recursion",
        "target_flag": "--url",
    },
    {
        "binary": "gobuster",
        "name": "gobuster",
        "phase": "vulnscan",
        "category": "fuzzing",
        "description": "Directory/DNS/vhost brute-forcing tool",
        "version_flag": "version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"Status: 200", r"Found:"],
        "install_hint": "apt install gobuster",
        "default_args": "dir -q",
        "target_flag": "-u",
    },
    {
        "binary": "dirsearch",
        "name": "dirsearch",
        "phase": "vulnscan",
        "category": "fuzzing",
        "description": "Web path discovery and enumeration",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"200\s+", r"301\s+"],
        "install_hint": "apt install dirsearch",
        "default_args": "--quiet",
        "target_flag": "-u",
    },
    {
        "binary": "wfuzz",
        "name": "wfuzz",
        "phase": "vulnscan",
        "category": "fuzzing",
        "description": "Web application fuzzer for params, headers, auth",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"200\s+", r"C=200"],
        "install_hint": "apt install wfuzz",
        "default_args": "--hc 404 -q",
        "target_flag": "-u",
    },
    {
        "binary": "sqlmap",
        "name": "sqlmap",
        "phase": "vulnscan",
        "category": "injection",
        "description": "Automatic SQL injection detection and exploitation",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"injectable", r"sql injection", r"\[WARNING\].*parameter"],
        "install_hint": "apt install sqlmap",
        "default_args": "--batch --level=1 --risk=1",
        "target_flag": "-u",
    },
    {
        "binary": "commix",
        "name": "commix",
        "phase": "vulnscan",
        "category": "injection",
        "description": "Command injection exploitation tool",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"vulnerable", r"command injection"],
        "install_hint": "apt install commix",
        "default_args": "--batch",
        "target_flag": "--url",
    },
    {
        "binary": "dalfox",
        "name": "dalfox",
        "phase": "vulnscan",
        "category": "injection",
        "description": "XSS scanner with WAF bypass and parameter analysis",
        "version_flag": "version",
        "timeout": 180,
        "output_fmt": "raw",
        "finding_patterns": [r"\[V\]", r"VULN", r"XSS"],
        "install_hint": "go install github.com/hahwul/dalfox/v2@latest",
        "default_args": "url --silence",
        "target_flag": "",
    },
    {
        "binary": "wpscan",
        "name": "wpscan",
        "phase": "vulnscan",
        "category": "cms",
        "description": "WordPress vulnerability scanner",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[!\]", r"\[+\].*vulnerable", r"CVE-"],
        "install_hint": "gem install wpscan",
        "default_args": "--no-banner",
        "target_flag": "--url",
    },
    {
        "binary": "joomscan",
        "name": "joomscan",
        "phase": "vulnscan",
        "category": "cms",
        "description": "Joomla vulnerability scanner",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[!\]", r"Vulnerable"],
        "install_hint": "apt install joomscan",
        "default_args": "",
        "target_flag": "-u",
    },
    {
        "binary": "droopescan",
        "name": "droopescan",
        "phase": "vulnscan",
        "category": "cms",
        "description": "Drupal and SilverStripe vulnerability scanner",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[+\]"],
        "install_hint": "pip install droopescan",
        "default_args": "scan drupal",
        "target_flag": "-u",
    },
    {
        "binary": "whatweb",
        "name": "whatweb",
        "phase": "vulnscan",
        "category": "fingerprint",
        "description": "Web technology fingerprinting",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"\[", r"WordPress", r"Apache"],
        "install_hint": "apt install whatweb",
        "default_args": "--color=never -a 3",
        "target_flag": "",
    },
    {
        "binary": "arjun",
        "name": "arjun",
        "phase": "vulnscan",
        "category": "param",
        "description": "HTTP parameter discovery tool",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"Found", r"parameter"],
        "install_hint": "pip install arjun",
        "default_args": "",
        "target_flag": "-u",
    },
    {
        "binary": "subjack",
        "name": "subjack",
        "phase": "vulnscan",
        "category": "subdomain_takeover",
        "description": "Subdomain takeover detection",
        "version_flag": "-h",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\[Vulnerable\]", r"\[Susceptible\]"],
        "install_hint": "go install github.com/haccer/subjack@latest",
        "default_args": "-ssl",
        "target_flag": "-w",
    },
    {
        "binary": "subzy",
        "name": "subzy",
        "phase": "vulnscan",
        "category": "subdomain_takeover",
        "description": "Subdomain takeover checker for cloud services",
        "version_flag": "version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"VULNERABLE"],
        "install_hint": "go install github.com/PentestPad/subzy@latest",
        "default_args": "run",
        "target_flag": "--target",
    },
    {
        "binary": "corscanner",
        "name": "corscanner",
        "phase": "vulnscan",
        "category": "misconfiguration",
        "description": "CORS misconfiguration scanner",
        "version_flag": "-h",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"vulnerable", r"CORS"],
        "install_hint": "pip install corscanner",
        "default_args": "",
        "target_flag": "-u",
    },
    {
        "binary": "jwt_tool",
        "name": "jwt_tool",
        "phase": "vulnscan",
        "category": "auth",
        "description": "JWT token analysis and attack tool",
        "version_flag": "--help",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"FOUND", r"vulnerable", r"alg=none"],
        "install_hint": "git clone github.com/ticarpi/jwt_tool",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "gitleaks",
        "name": "gitleaks",
        "phase": "vulnscan",
        "category": "secrets",
        "description": "Secret and credential leak detection in git repos",
        "version_flag": "version",
        "timeout": 120,
        "output_fmt": "json",
        "finding_patterns": [r"leak", r"secret", r"key"],
        "install_hint": "apt install gitleaks",
        "default_args": "detect --no-git",
        "target_flag": "--source",
    },
    {
        "binary": "trufflehog",
        "name": "trufflehog",
        "phase": "vulnscan",
        "category": "secrets",
        "description": "Find secrets in git history and live endpoints",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "json",
        "finding_patterns": [r"Found verified result"],
        "install_hint": "pip install trufflehog",
        "default_args": "filesystem --only-verified",
        "target_flag": "",
    },
    {
        "binary": "ssrfmap",
        "name": "ssrfmap",
        "phase": "vulnscan",
        "category": "injection",
        "description": "SSRF vulnerability detection and exploitation",
        "version_flag": "-h",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"vulnerable", r"SSRF"],
        "install_hint": "git clone github.com/swisskyrepo/SSRFmap",
        "default_args": "",
        "target_flag": "-u",
    },
    {
        "binary": "openvas",
        "name": "openvas",
        "phase": "vulnscan",
        "category": "webapp",
        "description": "Open vulnerability assessment system (GVM)",
        "version_flag": "--version",
        "timeout": 600,
        "output_fmt": "raw",
        "finding_patterns": [r"High", r"Critical", r"Medium"],
        "install_hint": "apt install openvas",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # VULN SCAN — Network & Infrastructure
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "sslscan",
        "name": "sslscan",
        "phase": "vulnscan",
        "category": "tls",
        "description": "TLS/SSL configuration analysis",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"SSLv2", r"SSLv3", r"TLSv1\.0", r"Heartbleed"],
        "install_hint": "apt install sslscan",
        "default_args": "--no-colour",
        "target_flag": "",
    },
    {
        "binary": "testssl.sh",
        "name": "testssl",
        "phase": "vulnscan",
        "category": "tls",
        "description": "Comprehensive TLS/SSL testing script",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"VULNERABLE", r"CRITICAL", r"HIGH"],
        "install_hint": "apt install testssl.sh",
        "default_args": "--quiet",
        "target_flag": "",
    },
    {
        "binary": "enum4linux",
        "name": "enum4linux",
        "phase": "vulnscan",
        "category": "smb",
        "description": "SMB/SAMBA enumeration for Windows targets",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\[\\+\]", r"user:", r"share:"],
        "install_hint": "apt install enum4linux",
        "default_args": "-a",
        "target_flag": "",
    },
    {
        "binary": "enum4linux-ng",
        "name": "enum4linux-ng",
        "phase": "vulnscan",
        "category": "smb",
        "description": "Next-gen SMB enumeration tool",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"FOUND", r"users:"],
        "install_hint": "pip install enum4linux-ng",
        "default_args": "-A",
        "target_flag": "",
    },
    {
        "binary": "snmpwalk",
        "name": "snmpwalk",
        "phase": "vulnscan",
        "category": "network",
        "description": "SNMP MIB walker for network device enumeration",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"STRING:", r"INTEGER:", r"OID:"],
        "install_hint": "apt install snmp",
        "default_args": "-c public -v2c",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # EXPLOIT
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "msfconsole",
        "name": "metasploit",
        "phase": "exploit",
        "category": "framework",
        "description": "Metasploit exploitation framework",
        "version_flag": "--version",
        "timeout": 600,
        "output_fmt": "raw",
        "finding_patterns": [r"session.*opened", r"Meterpreter"],
        "install_hint": "apt install metasploit-framework",
        "default_args": "-q",
        "target_flag": "",
    },
    {
        "binary": "searchsploit",
        "name": "searchsploit",
        "phase": "exploit",
        "category": "framework",
        "description": "ExploitDB offline search for CVEs and exploits",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [r"EDB-ID"],
        "install_hint": "apt install exploitdb",
        "default_args": "--colour",
        "target_flag": "",
    },
    {
        "binary": "beef-xss",
        "name": "beef",
        "phase": "exploit",
        "category": "browser",
        "description": "Browser exploitation framework",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"hooked", r"browser"],
        "install_hint": "apt install beef-xss",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # POST-EXPLOITATION & CREDENTIAL ATTACKS
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "hydra",
        "name": "hydra",
        "phase": "exploit",
        "category": "bruteforce",
        "description": "Online password brute-forcing across many protocols",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\[.*\].*login:", r"password:"],
        "install_hint": "apt install hydra",
        "default_args": "-q",
        "target_flag": "",
    },
    {
        "binary": "medusa",
        "name": "medusa",
        "phase": "exploit",
        "category": "bruteforce",
        "description": "Fast parallel network authentication brute-forcer",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"SUCCESS"],
        "install_hint": "apt install medusa",
        "default_args": "",
        "target_flag": "-h",
    },
    {
        "binary": "crackmapexec",
        "name": "crackmapexec",
        "phase": "exploit",
        "category": "network_auth",
        "description": "Post-exploitation tool for SMB, WinRM, LDAP, SSH",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\[\\+\]", r"Pwn3d!"],
        "install_hint": "apt install crackmapexec",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "netexec",
        "name": "netexec",
        "phase": "exploit",
        "category": "network_auth",
        "description": "Next-gen CrackMapExec successor",
        "version_flag": "--version",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"\[\\+\]", r"Pwn3d!"],
        "install_hint": "pip install netexec",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "responder",
        "name": "responder",
        "phase": "exploit",
        "category": "network_auth",
        "description": "LLMNR/NBT-NS/MDNS poisoner and credential catcher",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"NTLMv2", r"hash"],
        "install_hint": "apt install responder",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "impacket-secretsdump",
        "name": "secretsdump",
        "phase": "exploit",
        "category": "credentials",
        "description": "Remote SAM/NTDS/LSA secrets extraction via Impacket",
        "version_flag": "--help",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r":::"],
        "install_hint": "apt install impacket-scripts",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # PASSWORD CRACKING
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "john",
        "name": "john",
        "phase": "exploit",
        "category": "cracking",
        "description": "John the Ripper — password hash cracker",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"\(.*\)"],
        "install_hint": "apt install john",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "hashcat",
        "name": "hashcat",
        "phase": "exploit",
        "category": "cracking",
        "description": "GPU-accelerated password hash cracker",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"Cracked"],
        "install_hint": "apt install hashcat",
        "default_args": "--quiet",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # WIRELESS
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "aircrack-ng",
        "name": "aircrack-ng",
        "phase": "vulnscan",
        "category": "wireless",
        "description": "WEP/WPA/WPA2 cracking suite",
        "version_flag": "--help",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"KEY FOUND"],
        "install_hint": "apt install aircrack-ng",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "wifite",
        "name": "wifite",
        "phase": "vulnscan",
        "category": "wireless",
        "description": "Automated wireless network auditor",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"cracked", r"WPS PIN"],
        "install_hint": "apt install wifite",
        "default_args": "--quiet",
        "target_flag": "",
    },
    {
        "binary": "kismet",
        "name": "kismet",
        "phase": "recon",
        "category": "wireless",
        "description": "Wireless network detector and sniffer",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"found network"],
        "install_hint": "apt install kismet",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "reaver",
        "name": "reaver",
        "phase": "exploit",
        "category": "wireless",
        "description": "WPS brute-force attack tool",
        "version_flag": "--version",
        "timeout": 600,
        "output_fmt": "raw",
        "finding_patterns": [r"WPS PIN:", r"WPA PSK:"],
        "install_hint": "apt install reaver",
        "default_args": "",
        "target_flag": "-b",
    },
    {
        "binary": "bettercap",
        "name": "bettercap",
        "phase": "exploit",
        "category": "mitm",
        "description": "Network MITM attack framework",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"\[\\+\]"],
        "install_hint": "apt install bettercap",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # FORENSICS
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "volatility3",
        "name": "volatility",
        "phase": "forensics",
        "category": "memory",
        "description": "Memory forensics framework",
        "version_flag": "--version",
        "timeout": 300,
        "output_fmt": "raw",
        "finding_patterns": [r"Process", r"module"],
        "install_hint": "apt install volatility3",
        "default_args": "",
        "target_flag": "-f",
    },
    {
        "binary": "binwalk",
        "name": "binwalk",
        "phase": "forensics",
        "category": "firmware",
        "description": "Firmware analysis and extraction",
        "version_flag": "--help",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"DECIMAL", r"Zip archive", r"gzip"],
        "install_hint": "apt install binwalk",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "foremost",
        "name": "foremost",
        "phase": "forensics",
        "category": "carving",
        "description": "File carving and recovery tool",
        "version_flag": "-V",
        "timeout": 120,
        "output_fmt": "raw",
        "finding_patterns": [r"recovered"],
        "install_hint": "apt install foremost",
        "default_args": "",
        "target_flag": "-i",
    },
    {
        "binary": "autopsy",
        "name": "autopsy",
        "phase": "forensics",
        "category": "disk",
        "description": "Digital forensics platform",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install autopsy",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "strings",
        "name": "strings",
        "phase": "forensics",
        "category": "binary",
        "description": "Extract printable strings from binary files",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [r"password", r"key", r"secret", r"token"],
        "install_hint": "apt install binutils",
        "default_args": "-n 8",
        "target_flag": "",
    },
    {
        "binary": "exiftool",
        "name": "exiftool",
        "phase": "forensics",
        "category": "metadata",
        "description": "Read/write metadata from image and document files",
        "version_flag": "-ver",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [r"GPS", r"Author", r"Creator"],
        "install_hint": "apt install libimage-exiftool-perl",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # PRIVACY & ANONYMITY (Parrot-specific advantage)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "anonsurf",
        "name": "anonsurf",
        "phase": "util",
        "category": "anonymity",
        "description": "Parrot anonymous mode — routes all traffic through Tor",
        "version_flag": "--help",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "Parrot OS only: apt install anonsurf",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "proxychains4",
        "name": "proxychains",
        "phase": "util",
        "category": "anonymity",
        "description": "Proxy traffic through SOCKS4/5 or Tor chains",
        "version_flag": "--help",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install proxychains4",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # NETWORK UTILITIES
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "netcat",
        "name": "netcat",
        "phase": "util",
        "category": "network",
        "description": "TCP/UDP network utility — banner grabbing, port testing",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install netcat-traditional",
        "default_args": "-zv",
        "target_flag": "",
    },
    {
        "binary": "nc",
        "name": "nc",
        "phase": "util",
        "category": "network",
        "description": "Netcat (nc variant)",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install netcat",
        "default_args": "-zv",
        "target_flag": "",
    },
    {
        "binary": "socat",
        "name": "socat",
        "phase": "util",
        "category": "network",
        "description": "Multipurpose relay and tunnel tool",
        "version_flag": "-V",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install socat",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "tcpdump",
        "name": "tcpdump",
        "phase": "util",
        "category": "capture",
        "description": "Packet capture and analysis",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [r"password", r"Authorization"],
        "install_hint": "apt install tcpdump",
        "default_args": "-i any -n",
        "target_flag": "",
    },
    {
        "binary": "wireshark",
        "name": "wireshark",
        "phase": "util",
        "category": "capture",
        "description": "Network protocol analyser",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install wireshark",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "curl",
        "name": "curl",
        "phase": "util",
        "category": "http",
        "description": "HTTP client for header inspection and request crafting",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install curl",
        "default_args": "-sI --max-time 10",
        "target_flag": "",
    },
    {
        "binary": "wget",
        "name": "wget",
        "phase": "util",
        "category": "http",
        "description": "HTTP/FTP file retrieval",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install wget",
        "default_args": "-q --spider",
        "target_flag": "",
    },
    {
        "binary": "git",
        "name": "git",
        "phase": "util",
        "category": "vcs",
        "description": "Git — for cloning repos and secret scanning",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install git",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "jq",
        "name": "jq",
        "phase": "util",
        "category": "util",
        "description": "JSON processor for parsing tool output",
        "version_flag": "--version",
        "timeout": 10,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install jq",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "python3",
        "name": "python3",
        "phase": "util",
        "category": "lang",
        "description": "Python 3 interpreter",
        "version_flag": "--version",
        "timeout": 10,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install python3",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "ruby",
        "name": "ruby",
        "phase": "util",
        "category": "lang",
        "description": "Ruby interpreter (used by WPScan, Metasploit)",
        "version_flag": "--version",
        "timeout": 10,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install ruby",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "go",
        "name": "go",
        "phase": "util",
        "category": "lang",
        "description": "Go toolchain (needed for ProjectDiscovery tools)",
        "version_flag": "version",
        "timeout": 10,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install golang",
        "default_args": "",
        "target_flag": "",
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # WORDLIST / SUPPORT TOOLS
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "binary": "cewl",
        "name": "cewl",
        "phase": "util",
        "category": "wordlist",
        "description": "Custom wordlist generator from web content",
        "version_flag": "--version",
        "timeout": 60,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install cewl",
        "default_args": "",
        "target_flag": "",
    },
    {
        "binary": "crunch",
        "name": "crunch",
        "phase": "util",
        "category": "wordlist",
        "description": "Custom wordlist generator by pattern",
        "version_flag": "--version",
        "timeout": 30,
        "output_fmt": "raw",
        "finding_patterns": [],
        "install_hint": "apt install crunch",
        "default_args": "",
        "target_flag": "",
    },
]
